# Generated by Django 4.1.3 on 2022-12-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0002_customerlogup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlogup',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
    ]
