# Generated by Django 4.1.3 on 2023-03-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0012_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelation',
            field=models.BooleanField(default=True),
        ),
    ]
