# Generated by Django 4.1.3 on 2023-04-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0013_order_cancelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
