# Generated by Django 4.1.3 on 2023-08-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0019_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qnty_price',
            field=models.FloatField(default=1),
        ),
    ]
