# Generated by Django 4.1.3 on 2023-08-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0021_alter_order_qnty_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qnty_price',
        ),
    ]
