# Generated by Django 4.1.3 on 2023-08-11 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0024_alter_order_qnty_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150)),
                ('verify', models.BooleanField(default=False)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kookooleShop.customerlogup')),
            ],
        ),
    ]
