# Generated by Django 4.1.3 on 2023-08-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0025_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
