# Generated by Django 4.1.3 on 2023-08-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0026_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlogup',
            name='token',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customerlogup',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
