# Generated by Django 4.1.3 on 2023-08-17 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0029_alter_categories_root_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='root_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kookooleShop.rootcategories'),
        ),
    ]
