# Generated by Django 4.1.3 on 2023-08-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0030_alter_categories_root_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RootCategories',
            new_name='CategoriesRoot',
        ),
    ]
