# Generated by Django 4.1.3 on 2023-08-18 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0031_rename_rootcategories_categoriesroot'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='root_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kookooleShop.categoriesroot'),
        ),
    ]
