# Generated by Django 4.1.3 on 2023-09-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0036_alter_customerlogup_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlogup',
            name='password_reset_token',
            field=models.CharField(default='', max_length=150),
        ),
    ]
