# Generated by Django 4.1.3 on 2023-09-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0037_customerlogup_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlogup',
            name='profile_img',
            field=models.URLField(),
        ),
    ]
