# Generated by Django 4.1.3 on 2023-09-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0039_alter_customerlogup_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlogup',
            name='password_reset_token',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customerlogup',
            name='profile_img',
            field=models.URLField(blank=True, default='media/kookoole.png'),
        ),
    ]
