# Generated by Django 4.1.3 on 2023-09-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0040_alter_customerlogup_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlogup',
            name='password_reset_token',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customerlogup',
            name='profile_img',
            field=models.URLField(default='media/kookoole.png'),
        ),
    ]
