# Generated by Django 4.1.3 on 2023-11-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0043_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
