# Generated by Django 4.1.3 on 2023-11-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookooleShop', '0044_delete_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='', max_length=13)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.URLField(default='https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d7660527.340719109!2d85.82489999999999!3d20.362600000000008!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1695367904279!5m2!1sen!2sin')),
            ],
        ),
    ]
